version: '3.8'
services:
  app:
    container_name: almatar_loyalty_app
    build: .
    networks:
      - almatar_network
    ports:
      - "${SERVER_PORT:-3000}:3000"
    depends_on:
      - postgres_db
  postgres_db:
    container_name: almatar_loyalty_postgres
    image: postgres:latest
    restart: always
    networks:
      - almatar_network
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${DB_USERNAME:-almatar}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-almatar}"
      POSTGRES_DB: "${DB_NAME:-almatar}"
    volumes:
      - almatar_postgres_data_container:/var/lib/postgresql/data

networks:
  almatar_network:
    driver: bridge

volumes:
  almatar_postgres_data_container: